### ISSUE TITLE
Missing libappimage.so

### ISSUE THREAD

**Issue by JuPlutonic** [AppImageCrafters/appimage-manager#4]
All apps installed with error

```
Integration failed: missing libappimage.so
```

Some applications (e.g. appimagehub:1297572) got desktop integration inside container, so I think this error is not critical.
OS: ElementaryOS Hera - 18.04.10Ubuntu Linux 5.4.0.54-generic x86_64 (error appeared on different notebooks).
apt-file search libappimage.so - empty list 👨‍🔧️.

**Comment by azubieta** [comment]
Sorry for the late response, libappimage.so is provided by https://github.com/AppImage/libappimage
So you must install it before using appimage-manager.

Or use AppImage file from releases section, this already include it.

**Comment by JuPlutonic** [comment]
Thank you!
`squashfs-root/usr/lib/x86_64-linux-gnu/libappimage.so.1.0.2`
